# Generated by Django 2.2.5 on 2019-09-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arq_vilao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
            ],
        ),
        migrations.CreateModel(
            name='Habilidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('nivel_habilidade', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Heroi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('fraqueza', models.CharField(max_length=255, verbose_name='fraqueza')),
            ],
        ),
        migrations.DeleteModel(
            name='Habilidades',
        ),
        migrations.DeleteModel(
            name='Herois',
        ),
        migrations.RenameModel(
            old_name='Universos',
            new_name='Universo',
        ),
        migrations.AddField(
            model_name='heroi',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Universo'),
        ),
        migrations.AddField(
            model_name='habilidade',
            name='hab_heroi',
            field=models.ManyToManyField(related_name='habilidade', to='landing.Heroi'),
        ),
        migrations.AddField(
            model_name='arq_vilao',
            name='hab_vilao',
            field=models.ManyToManyField(related_name='Arq_vilao', to='landing.Habilidade'),
        ),
        migrations.AddField(
            model_name='arq_vilao',
            name='heroi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Heroi'),
        ),
        migrations.AddField(
            model_name='arq_vilao',
            name='universo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landing.Universo'),
        ),
    ]
